version: '3'

services:
  memcached1:
    image: memcached:latest
    container_name: memcached1
    ports:
      - "11211:11211"
  python-client1:
    build: ./src
    container_name: python-client1
    depends_on:
      - memcached1
    environment:
      - PYTHONUNBUFFERED=1
      - MEMCACHED_SERVERS=memcached1:11211
    tty: true
  python-client2:
    build: ./src
    container_name: python-client2
    depends_on:
      - memcached1
    environment:
      - PYTHONUNBUFFERED=1
      - MEMCACHED_SERVERS=memcached1:11211
    tty: true
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - python-client1
      - python-client2
    volumes:
      - ./nginx-dynamic.conf:/etc/nginx/nginx.conf:ro
